#!/bin/bash

RESP=$(cat <<EOF | dmenu -i
Logout
Sleep
Reboot
Shutdown
EOF
);

case "$RESP" in
	Logout)
		swaymsg exit
		;;
	Sleep)
		systemctl suspend
		;;
	Reboot)
		systemctl reboot
		;;
	Shutdown)
		systemctl poweroff
		;;
	*)
		exit 1
esac
