local myutils = require("myutils")

vim.keymap.set("n", "<leader>pv", vim.cmd.Ex, { desc = "Explorer" })
vim.keymap.set("n", "<leader>bd", vim.cmd.bd, { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>qf", function() vim.cmd("qa!") end, { desc = "Force quit" })
vim.keymap.set("n", "<leader>qa", ":qa<CR>", { desc = "Quit all" })
vim.keymap.set("n", "<leader>qw", vim.cmd.xa, { desc = "Quit writing all" })
vim.keymap.set("n", "<leader>qq", vim.cmd.q, { desc = "Quit" })
vim.keymap.set("n", "<leader>uh", vim.cmd.noh, { desc = "Clear highlight" })
vim.keymap.set("n", "<leader>uus", ":mksession! " .. myutils.SESSION_FILE .. "<CR>", { desc = "Save session to default file" })
vim.keymap.set({ "n", "i", "v" }, "<C-s>", vim.cmd.w)

local telescope = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", telescope.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fj", telescope.jumplist, { desc = "Telescope find jumplist" })
vim.keymap.set("n", "<C-p>", telescope.git_files, { desc = "Telescope find files in git" })
vim.keymap.set("n", "<leader>fg", telescope.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", telescope.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", telescope.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>fk", telescope.keymaps, { desc = "Telescope keymaps" })
vim.keymap.set("n", "<leader>fm", telescope.marks, { desc = "Telescope marks" })
vim.keymap.set("n", "<C-/>", telescope.current_buffer_fuzzy_find, { desc = "Telescope find fuzzy in current buffer" })
