local myutils = require("myutils")

vim.keymap.set("n", "<leader>pv", "<cmd>tabnew<cr><cmd>NvimTreeOpen<cr><c-w>l<cmd>bd<cr>", { desc = "Explorer" })
vim.keymap.set("n", "<leader>bd", vim.cmd.bd, { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>bD", "<cmd>bd!<cr>", { desc = "Delete buffer without saving" })
vim.keymap.set("n", "<leader>bt", ":tabnew %<cr><c-tab><c-o><c-tab>", { desc = "Move buffer to separate tab" })
vim.keymap.set("n", "<leader>qf", function() vim.cmd("qa!") end, { desc = "Force quit" })
vim.keymap.set("n", "<leader>qa", "<cmd>qa<cr>", { desc = "Quit all" })
vim.keymap.set("n", "<leader>qw", vim.cmd.xa, { desc = "Quit writing all" })
vim.keymap.set("n", "<leader>qq", vim.cmd.q, { desc = "Quit" })
vim.keymap.set("n", "<leader>uh", vim.cmd.noh, { desc = "Clear highlight" })
vim.keymap.set("n", "<leader>uz", "<cmd>UndotreeToggle<cr><cmd>UndotreeFocus<cr>", { desc = "Toggle and focus undo tree" })
vim.keymap.set("n", "<leader>uus", "<cmd>mksession! " .. myutils.SESSION_FILE .. "<cr>", { desc = "Save session to default file" })
vim.keymap.set({ "n", "i", "v" }, "<C-s>", vim.cmd.w, { desc = "Write buffer" })
vim.keymap.set("v", "J", "<cmd>m '>+1<cr>gv=gv")
vim.keymap.set("v", "K", "<cmd>m '<-2<cr>gv=gv")
vim.keymap.set("x", "<leader>p", "\"_dP", { desc = "Paste without saving" })
vim.keymap.set({"n","v"}, "<leader>y", "\"+y", { desc = "Yank to system clipboard" })
-- vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set({"n","v"}, "<leader>ud", "\"_d", { desc = "Delete to void" })
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("i", "<c-c>", "<esc>")
vim.keymap.set("n", "<leader>sr", ":%s/", { desc = "Search and replace" })
vim.keymap.set("v", "O", "$o^")
vim.keymap.set("n", "<leader>ft", vim.cmd.NvimTreeFindFileToggle, { desc = "Find file in tree" })

vim.keymap.set("n", "<leader>fG", function()
  local search = vim.fn.input("ripgrep > ")
  local escaped, _ = string.gsub(search, "([\\\'\"<>()])", "\\%1")
  vim.cmd("tabnew | silent r !rg " .. escaped .. " || echo No results")
  local timestamp = os.time(os.date("!*t"))
  local fname = "/tmp/rg_" .. timestamp .. "_" .. string.gsub(search, "[\\W-]", "_"):sub(1, 10)
  vim.cmd("f " .. fname)
end, { desc = "ripgrep to new buffer" })

local telescope = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", telescope.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fj", telescope.jumplist, { desc = "Telescope find jumplist" })
vim.keymap.set("n", "<C-p>", telescope.git_files, { desc = "Telescope find files in git" })
vim.keymap.set("n", "<leader>fg", telescope.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", telescope.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", telescope.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>fk", telescope.keymaps, { desc = "Telescope keymaps" })
vim.keymap.set("n", "<leader>fm", telescope.marks, { desc = "Telescope marks" })
vim.keymap.set("n", "<C-/>", telescope.current_buffer_fuzzy_find, { desc = "Telescope find fuzzy in current buffer" })
